Exception: STATUS_ACCESS_VIOLATION at rip=7FFB613C5617
rax=000006FE28F00010 rbx=000006FE28F00010 rcx=000006FFFFF3FFD0
rdx=0000000000000000 rsi=000000003ADE68B0 rdi=00000001D6F34580
r8 =FFFFFFFFD6F34580 r9 =0000000000000000 r10=03FFFFFFF7FFBD17
r11=000000053BBA0655 r12=0000000000000000 r13=00000000FFFFFFFF
r14=00000006000CFB50 r15=000006FFFFF3199F
rbp=000006FFFFE42830 rsp=000000000023A288
program=C:\cygwin64\bin\python2.7.exe, pid 2760, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
6FFFFE42830  7FFB613C5617 (00000000071, 0000023A7C0, 6FFFFE42830, 6FE28F00010)
6FFFFE42830  7FFB5FC2D2D6 (00000000000, 000FFFFFFFF, 6FFFFE4AC20, 6FFFFE4AC20)
6FFFFE42830  001800C5967 (0053BCE3A0A, 0000000000F, 7FFB5FC2D2D6, 6FFFFE42830)
6FFFFE42830  0053BBA066B (001800C5967, 0000023A360, 0000023A370, 0000023A380)
6FFFFE42830  0053BC2059B (001800C5967, 6FFFFE42B48, 6FFFFE42830, 00000000002)
6FFFFE42830  0053BC274AD (6FFFFEB2F10, 6FFFFFC0050, 6FFFFFC0050, 00000000000)
00600010500  0053BC27796 (0053BB9D570, 01F00000002, 00000000009, 00000000000)
00000000000  0053BC27FA2 (00000000000, 6FFFFE4A878, 006000111F0, 00100000000)
6FFFFF15168  0053BC280EF (001801B1103, 0000023A960, 00000000001, 0000023A890)
6FFFFF15168  0053BC56174 (001802E3F98, 0060002AE40, 000801135DB, 6FFFFF15168)
001802E3BF8  0053BC57B33 (00000000000, 00180046730, 0018013C0D9, 00180174D30)
6FFFFE68660  0053BC6E870 (00000000020, 30001000000FF00, 00180048270, 00000000000)
0000023AB90  001800482E1 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0018004619B (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  001800462F4 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  001004010F1 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace (more stack frames may be present)
